---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc4-snmp-traps
  labels:
    app: sc4-snmp-traps
    # environment: production
    # tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc4-snmp-traps
      # environment: production
      # tier: frontend
  template:
    metadata:
      labels:
        app: sc4-snmp-traps
        # environment: production
        # tier: frontend
    spec:
      containers:
        - name: traps
          image: ghcr.io/splunk/splunk-connect-for-snmp-traps:latest
          args: ["--loglevel=DEBUG", "--config=/work/config.yaml", "--index=snmp"]
          ports:
            - name: trap-port
              containerPort: 2162
              protocol: UDP
          env:
            - name: MIBS_SERVER_URL
              value: http://$(MIB_SERVER_SERVICE_SERVICE_HOST):$(MIB_SERVER_SERVICE_SERVICE_PORT)
            - name: SPLUNK_HEC_URL
              valueFrom:
                secretKeyRef:
                  name: remote-splunk
                  key: SPLUNK_HEC_URL
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: remote-splunk
                  key: SPLUNK_HEC_TOKEN
            - name: SPLUNK_HEC_TLS_VERIFY
              valueFrom:
                secretKeyRef:
                  name: remote-splunk
                  key: SPLUNK_HEC_TLS_VERIFY
      imagePullSecrets:
        - name: regcred
---

