apiVersion: v1
kind: Service
metadata:
  name: mib-server-service
spec:
  type: LoadBalancer
  loadBalancerIP: replace-me
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: sc4-snmp-mib-server