apiVersion: apps/v1
kind: Deployment
metadata:
  name: mib-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc4-snmp-mib-server
  template:
    metadata:
      labels:
        app: sc4-snmp-mib-server
    spec:
      containers:
        - name: mib-server
          image: ghcr.io/splunk/splunk-connect-for-snmp-mib-server:41871098f40607f6d035d42b26db9f241e81e2df
          ports:
            - containerPort: 5000
          env:
            - name: MIBS_SERVER_URL
              value: "http://$(MIB_SERVER_SERVICE_SERVICE_HOST):$(MIB_SERVER_SERVICE_SERVICE_PORT)/files/asn1/@mib@"
---
