---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc4-snmp-worker
  labels:
    app: sc4-snmp-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc4-snmp-worker
  template:
    metadata:
      labels:
        app: sc4-snmp-worker
    spec:
      containers:
        - name: sc4-snmp-worker
          # image: luca/test-worker-3
          # TODO: not sure what image I should put it for now.
          image: ghcr.io/splunk/splunk-connect-for-snmp-poller:589bf49e73b997b99c371f1d260a120dc2e365ce
          #imagePullPolicy: Never
          ports:
            - containerPort: 2162
          env:
            - name: CELERY_BROKER_URL
              value: amqp://guest@$(RABBITMQ_SERVICE_SERVICE_HOST):$(RABBITMQ_SERVICE_SERVICE_PORT)//
            - name: POLLER_EXECUTION_MODE
              value: worker
      imagePullSecrets:
        - name: regcred




